# === STARSHIP CONFIG ===
format = "$all"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[git_branch]
symbol = " "
style = "bold purple"

[directory]
style = "bold blue"
read_only = " 󰌾"
